### PR TITLE
Updated Titles (v1.2)

### PR DESCRIPTION
**Pull request by DragonVirus**

### CODE REVIEW

**Comment by acorbi** [comment]
@DragonVirus what Issue or feature request does this PR fix/address?

**Comment by DragonVirus** [comment]
@acorbi it's design and some flow fix from this https://drive.google.com/file/d/12Cp3OeVppWbEI3N3YNO4CoWtW6TzdSx9/view?usp=sharing

**Comment by acorbi** [comment]
@DragonVirus out of curiosity.... where is this being used?

**Comment by DragonVirus** [comment]
@acorbi It is to create StoryMap at https://storymap.knightlab.com/

**Comment by acorbi** [comment]
:+1:

**Pull request merged**
